final Map<String, String> testUser = {
  "email": 'bob@somedomain.com',
  "password": ""
};

String nhtsaTestData = '''
            {
  "Count": 1,
  "Message": "Results returned successfully. NOTE: Any missing decoded values should be interpreted as NHTSA does not have data on the specific variable. Missing value should NOT be interpreted as an indication that a feature or technology is unavailable for a vehicle.",
  "SearchCriteria": "VIN(s): 2CNFLEEW5A6267165",
  "Results": [
    {
      "ABS": "",
      "ActiveSafetySysNote": "",
      "AdaptiveCruiseControl": "",
      "AdaptiveDrivingBeam": "",
      "AdaptiveHeadlights": "",
      "AdditionalErrorText": "",
      "AirBagLocCurtain": "",
      "AirBagLocFront": "1st Row (Driver and Passenger)",
      "AirBagLocKnee": "",
      "AirBagLocSeatCushion": "",
      "AirBagLocSide": "1st Row (Driver and Passenger)",
      "AutoReverseSystem": "",
      "AutomaticPedestrianAlertingSound": "",
      "AxleConfiguration": "",
      "Axles": "",
      "BasePrice": "",
      "BatteryA": "",
      "BatteryA_to": "",
      "BatteryCells": "",
      "BatteryInfo": "",
      "BatteryKWh": "",
      "BatteryKWh_to": "",
      "BatteryModules": "",
      "BatteryPacks": "",
      "BatteryType": "",
      "BatteryV": "",
      "BatteryV_to": "",
      "BedLengthIN": "",
      "BedType": "",
      "BlindSpotIntervention": "",
      "BlindSpotMon": "",
      "BodyCabType": "",
      "BodyClass": "Sport Utility Vehicle (SUV)/Multi-Purpose Vehicle (MPV)",
      "BrakeSystemDesc": "",
      "BrakeSystemType": "Hydraulic",
      "BusFloorConfigType": "Not Applicable",
      "BusLength": "",
      "BusType": "Not Applicable",
      "CAN_AACN": "",
      "CIB": "",
      "CashForClunkers": "",
      "ChargerLevel": "",
      "ChargerPowerKW": "",
      "CoolingType": "",
      "CurbWeightLB": "",
      "CustomMotorcycleType": "Not Applicable",
      "DaytimeRunningLight": "",
      "DestinationMarket": "",
      "DisplacementCC": "2400.0",
      "DisplacementCI": "146.45698582735",
      "DisplacementL": "2.4",
      "Doors": "4",
      "DriveType": "AWD/All-Wheel Drive",
      "DriverAssist": "",
      "DynamicBrakeSupport": "",
      "EDR": "",
      "ESC": "",
      "EVDriveUnit": "",
      "ElectrificationLevel": "",
      "EngineConfiguration": "",
      "EngineCycles": "",
      "EngineCylinders": "4",
      "EngineHP": "",
      "EngineHP_to": "",
      "EngineKW": "",
      "EngineManufacturer": "GMNA",
      "EngineModel": "LAF",
      "EntertainmentSystem": "",
      "ErrorCode": "0",
      "ErrorText": "0 - VIN decoded clean. Check Digit (9th position) is correct",
      "ForwardCollisionWarning": "",
      "FuelInjectionType": "",
      "FuelTypePrimary": "Gasoline",
      "FuelTypeSecondary": "",
      "GCWR": "",
      "GCWR_to": "",
      "GVWR": "Class 1D: 5,001 - 6,000 lb (2,268 - 2,722 kg)",
      "GVWR_to": "",
      "KeylessIgnition": "",
      "LaneCenteringAssistance": "",
      "LaneDepartureWarning": "",
      "LaneKeepSystem": "",
      "LowerBeamHeadlampLightSource": "",
      "Make": "CHEVROLET",
      "MakeID": "467",
      "Manufacturer": "GENERAL MOTORS LLC",
      "ManufacturerId": "984",
      "Model": "Equinox",
      "ModelID": "1847",
      "ModelYear": "2010",
      "MotorcycleChassisType": "Not Applicable",
      "MotorcycleSuspensionType": "Not Applicable",
      "NCSABodyType": "",
      "NCSAMake": "",
      "NCSAMapExcApprovedBy": "",
      "NCSAMapExcApprovedOn": "",
      "NCSAMappingException": "",
      "NCSAModel": "",
      "NCSANote": "",
      "NonLandUse": "",
      "Note": "",
      "OtherBusInfo": "",
      "OtherEngineInfo": "SIDI, VVT, ALUM",
      "OtherMotorcycleInfo": "",
      "OtherRestraintSystemInfo": "Airbags: Roof Side (all seating rows)",
      "OtherTrailerInfo": "",
      "ParkAssist": "",
      "PedestrianAutomaticEmergencyBraking": "",
      "PlantCity": "INGERSOLL",
      "PlantCompanyName": "CAMI",
      "PlantCountry": "CANADA",
      "PlantState": "ONTARIO",
      "PossibleValues": "",
      "Pretensioner": "",
      "RearAutomaticEmergencyBraking": "",
      "RearCrossTrafficAlert": "",
      "RearVisibilitySystem": "",
      "SAEAutomationLevel": "",
      "SAEAutomationLevel_to": "",
      "SeatBeltsAll": "Manual",
      "SeatRows": "",
      "Seats": "",
      "SemiautomaticHeadlampBeamSwitching": "",
      "Series": "",
      "Series2": "",
      "SteeringLocation": "",
      "SuggestedVIN": "",
      "TPMS": "Direct",
      "TopSpeedMPH": "",
      "TrackWidth": "",
      "TractionControl": "",
      "TrailerBodyType": "Not Applicable",
      "TrailerLength": "",
      "TrailerType": "Not Applicable",
      "TransmissionSpeeds": "",
      "TransmissionStyle": "",
      "Trim": "1LT",
      "Trim2": "",
      "Turbo": "",
      "VIN": "2CNFLEEW5A6267165",
      "ValveTrainDesign": "Dual Overhead Cam (DOHC)",
      "VehicleDescriptor": "2CNFLEEW*A6",
      "VehicleType": "MULTIPURPOSE PASSENGER VEHICLE (MPV)",
      "WheelBaseLong": "",
      "WheelBaseShort": "",
      "WheelBaseType": "",
      "WheelSizeFront": "",
      "WheelSizeRear": "",
      "Wheels": "",
      "Windows": ""
    }
  ]
}
          ''';
